### ISSUE TITLE
QGIS tool for initializing the land use plan database in PostGIS

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#1]
# Button for PostGIS-connection

Land use planner needs to establish a connection to PostGIS database and run the initialization sql for land use planning database. At the moment there are 2 possible database models to run: [a detailed land use plan database model](https://github.com/GispoCoding/qaava/tree/master/asemakaavan-tietomalli) and a general plan database model.

## User story:

1. Land use planner opens QGIS and downloads the QAAVA plugin 
2. Land use planner clicks the designated button for initialization of the land use database 
3. User chooses which land use plan database they want (2 options at the moment, slightly different models)
4. Users connects to existing PostGIS database 
5. With "run" the database is set-up

## Questions:

-  If the user do not have their own PostGIS set-up, we can offer maybe SAAS-service or options for possible service providers?
- Does the user need to have an ability to add some needed information to the database with a form? And what information?
- Does the user have the possibility to add other users rights to the database?
- After the set-up, do we need a button that opens the needed datasets with relations and forms to the QGIS project? In this case, maybe a ready made QGIS profile with connections to the right database.

**Comment by Joonalai** [comment]
>  
> * After the set-up, do we need a button that opens the needed datasets with relations and forms to the QGIS project? In this case, maybe a ready made QGIS profile with connections to the right database.

@SannaJokela It is possible to add the needed datasets with relations and forms to the project programmatically as well. I think it should be discussed whether this plugin should be used as stand-alone without any QGIS project file or profile or should it be used with one. In any case I think a separate issue should be made for that.

**Comment by SannaJokela** [comment]
@Joonalai if it can be done without QGIS project, it would be great! If the attribute forms and relations can be created without the need for a QGIS project, it will solve multiple things, I think.

**Comment by Joonalai** [comment]
@SannaJokela Yes, I agree. This would however require a bit more work and specifications.
