### ISSUE TITLE
Review and re-design UI of the dialogs

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/qaava-qgis-plugin#17]
For this task [QT Designer](https://build-system.fman.io/qt-designer-download) (link not tested, use [official](https://www.qt.io/download-qt-installer) if needed.)

Open every *.ui* file and review the design. You can modify the design with QT Designer as long as the names of the components remain the same. If major changes are required, you can create whole new design and commit it and someone else could implement the logic with Python if needed.

This issue should be done when majority of the UI functionality is ready.

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
