### ISSUE TITLE
Adding land use plan elements (features)

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#3]
# Tool for adding land use features (polygons, lines, points)

Idea of the tool is to help the land use planner to add new land use elements and additional features to the map. All the features are linked to the core element (border=polygon) of the land use plan in the database model. 

There are at least 4-5 different feature types with slightly different attributes depending on the land use plan model (check the land use model for more information):

- zoning elements (polygons) 
- sub-regions (polygons)
- other elements (polygons, points, lines)

## User story 1
Assumption: 

- the land use planner has already initialized a connection to the database (#1).
- the border of the land use plan with basic information has been established (#2) 

1. Land use planner clicks the "create a land use feature" button(s) and a empty layer(s) appears to the QGIS layer list. 
2. Land use planner clicks the layer editable and digitizes the feature
3. When finishing, an attribute form pops open and the land use planner chooses the necessary information for the object. The dates and user information are automatically saved to the database. If the feature is part of the same land use plan that has been used previously with the QAAVA-tools, the relation to the border element is set to default. 
4. Afterwards or at the same time, the land use planner can add additional information to the feature like land use specification and linked documents.

## Questions:

-

**Comment by mvaaltola** [comment]
No need for a separate tool at this point.
