### ISSUE TITLE
Tool for updating attribute information for existing land use plan elements

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#4]
# Tool for updating the land use plan features

The idea of this tool is to update multiple land use features at the same time by adding same attribute values to selected features.  

Fields that usually are to be updated jointly are at least the following: 

- dates (different types in the database)
- land use specification (list with available specifications and a add a new specification, if not in the list)
- process step/value
- adding source information (link to original dataset). 

## User story
Land use planner wants to add the same land use specification information to several land use features.

1. Land use planner chooses the features that are to be updated from the map view or from attribute table
2. Land use planner clicks a QAAVA-tool called "Add information to several land use elements"
3. A form opens, where you the land use planner can set wanted values from a list to selected features or in some cases add new values to the lists. 

## Questions
-

**Comment by SannaJokela** [comment]
You can already select multiple features and change attributes accordingly.

**Comment by Joonalai** [comment]
Updatable values: Numerical value, theme, kaavamääräys, document

**Comment by SannaJokela** [comment]
Problems solved with QGIS profile & relations
