### ISSUE TITLE
Adding land use features from existing dataset of WFS

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#5]
# Adding new elements based on existing dataset or WFS

In some cases the land use planner uses ready made datasets (.shp, .gpkh, .mif) or WFS to add needed features to the land use plan database. There have been problems with handling unique ID's and different field types. This tool should help to map the needed fields and attributes to corresponding layer and field in the land use plan database. The process provides a new unique ID for the new feature but also if available, adds the globally unique ID to the database. Example datasets to be added from different sources are e.g. ground water areas or protected sites. 

## User story

1. Land use planner has added a new layer to QGIS and wants to copy some of the vector features to the land use plan
2. User selects the needed features from the map or attribute form
3. User clicks a QAAVA-tool called "Add features from existing layer" and a form pops open
4. In the form the user can choose to add only the selected features to the land use plan or the whole dataset. User also chooses which layer the selected features are to be added (only one option can be selected, if source dataset is polygon, only polygon layers are active). 
5. User clicks "Add" and the form asks the user what fields are to be compared. ID's and other information are generated automatically. 

## Example datasets
- [SYKE WFS](https://geoserver.ymparisto.fi/geoserver/wfs?service=wfs&version=2.0.0&request=GetCapabilities) (some issues with certificates??)
- [NHA (Museovirasto)](http://kartta.nba.fi/arcgis/services/WFS/MV_KulttuuriymparistoSuojellut/MapServer/WFSServer)
- Testdatasets in GD from Seinäjoki & Espoo (general plan)
- [Tampere WFS:](https://geodata.tampere.fi/geoserver/ows?service=WFS&version=1.0.0&request=GetCapabilities) e.g. layer Yleiskaava 2040 kartta2 käyttötarkoitusalueet

## Questions
- If the existing dataset has different format fields, how can we tackle this?

## Possible solution
- City of Tampere has done work with similar tools (Y-työkalu)

**Comment by SannaJokela** [comment]
Refractor tool ==> temp layer to schema ==> database? Links to Museovirasto & SYKE needed. What do we need from the source datasets? Geometry + source information (foreignID). Do we need some more information?

**Comment by Joonalai** [comment]
@mvaaltola you mentioned that you had some idea of how to go on with this. Would you like to explain the idea in few bullet points?

**Comment by mvaaltola** [comment]
My idea was to implement a simple form where the user first chooses a layer to import from and a target table. After they have been selected, a "mapping" form is populated based on the fields of the selected layer and the columns of the selected db table.

The user then picks which field corresponds to which column and clicks import. A new qgsvectorlayer is created with field names and types matching the db table columns. The new layer is populated with features from the original layer, based on the mapping the user has done. Finally, the new layer is appended to the db table using a suitable qgis processing alg.

This way users can import data from a single layer to a single table in a somewhat straightforward way. Adding capability to import from one layer to multiple tables would complicate the solution and may not be required.

Here's a basic UI sketch: 
![image](https://user-images.githubusercontent.com/33040018/94276944-8eb6cd00-ff51-11ea-98ac-0b2b994b670f.png)

**Comment by Joonalai** [comment]
@mvaaltola the idea is great! Thank you for the commit as well! :blush:

**Comment by Joonalai** [comment]
@SannaJokela could you perhaps give some mapping examples in format `wfsurl`:`layer` -> `yleiskaava/asemakaava`: `layer_in_QGIS_project` (additional info)?
For example:
* https://geoserver.ymparisto.fi/geoserver/wfs: HydroNode -> yleiskaava: Kaavaelementti - piste (take only features that match: gml_id >= hy-n-5007090602267)

**Comment by SannaJokela** [comment]
Bringing protected buildingings: http://kartta.nba.fi/arcgis/services/WFS/MV_KulttuuriymparistoSuojellut/MapServer/WFSServer: WFS_MV_KulttuuriymparistoSuojellut:Suojellut_rakennukset_piste -> yleiskaava: Kaavaelementti - piste (uuid=inspireID(?) + possibly luomispvm=suojeluPäätöspvm). In this case the "gid_kaavaelementti_tyyppi" should also be updated, but I think it is better that the land use planner does this. 

Bringing features from an existing land use plan: https://geodata.tampere.fi/geoserver/ows: maankaytto:yk2040_k2_V_AV_CV_SL_kayttotark_polygon_hho_paatos_GSVIEW ==> yleiskaava: maankayttoalue (kayttotarkoitus=gid_maankayttoluokka ==> problem? gid_maankayttoluokka is integer and kayttotarkoistus string)

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
