### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#55]
Foreign key constraint error for many-to-many relations when trying to delete features. Throws an error like: 

PostGIS error while deleting features: ERROR: update or delete on table "maankayttoalue" violates foreign key constraint "maankayttoalue_fk" on table "many_maankayttoalue_has_many_kaavamaarays"
             DETAIL: Key (uuid)=(ec841bd0-f275-4431-9158-e081d5884ece) is still referenced from table "many_maankayttoalue_has_many_kaavamaarays".

This affects both asemakaava and yleiskaava QGIS projects and all spatial layers and all relations.

**Comment by Joonalai** [comment]
@SannaJokela this should be issue for qaava project, not qaava-qgis-project I think.

**Comment by SannaJokela** [comment]
@Joonalai ok. Sorry :)
