### ISSUE TITLE
Translate QAAVA-tool to Swedish

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#60]
Swedish translations needed.

**Comment by Joonalai** [comment]
What about SQL schema? Should it for example have PostgreSQL comments in different languages?

**Comment by SannaJokela** [comment]
Added another issue with the QGIS projects: https://github.com/GispoCoding/qaava/issues/35 

Most of the comments can be tackled with QGIS project configurations. We have to discuss if the PostgreSQL comments and the whole database should be in English... Currently the national land use database model is done in Finnish.

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
