### ISSUE TITLE
Trying to open a QGIS project from a database without authentication crashes QGIS

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/qaava-qgis-plugin#62]
Currently, it is possible to have a database set up with no authentication. In this case, QGIS prompts the user to give username and password when connecting.

However, when opening a project in such a database, username and password from the Qt dialog are left empty, causing a database connection with FATAL: role "None" does not exist, and crashing QGIS.

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
