### ISSUE TITLE
Update the project to use latest development resources

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/qaava-qgis-plugin#63]
Update at least
- [ ] requirements.txt
- [ ] qgis_plugin_tools
- [ ] issue templates
- [ ] workflows
- [ ] pre-commit from qgis_plugin_tools/infrastructure/template/root (also configuration files)
- [ ] Use different log directory and teardown logger (see qgis_plugin_tools custom_logger.py commit messages)
- [ ] development.md

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
