### ISSUE TITLE
Dividing features while keeping the database integrity 

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#7]
# Dividing land use features and allowing user to choose if the attributes are inherited

Since the land use plan database is a relational model, the data integrity must stay also intact when splitting features. 

## User story:
1. Land use planner has added a land use element with relations to needed tables
2. Land use planners splits the feature into two features and 1) allows the other part of the feature to inherit the same attributes as the  original one or 2) decides that the new feature will have different attributes than the original.
3. The new feature is saved with wanted attributes and relations are intact.

## Questions:
- How to keep relations with land use specification #6 and land use plan border #2 when cutting or splitting objects?

**Comment by Joonalai** [comment]
@SannaJokela the existing functionality of splitting keeps the attribute values on both parts the same. Is this the wanted behaviour?

**Comment by SannaJokela** [comment]
@Joonalai ok, good! Does it keep the attributes of the relations also? If so, this is ok and wanted behaviour. The user can then change the values if needed.

**Comment by Joonalai** [comment]
@SannaJokela yes it does, I tested that as well. I will close the issue now.
