### ISSUE TITLE
Handling history information

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava-qgis-plugin#9]
# Versioning and history information for land use planning elements

PostGIS database should store information about all the different changes to the data. But the most crucial information that is needed is to store the cross sections of land use plan when it has been moved to another land use planning phase (process step general) e.g from "in the process of adoption" to "legally binding or active". This cross section information needs to be stored and accessible through QGIS (maybe take into account also in #8) 

## User story:
1. Land use planner needs to get access to the land use plan data that was under elaboration in year 2020.
2. Land use planner clicks #8 and chooses the needed query and receives the data with all layers as it was n the elaboration phase. 

## Questions:
- Can this cross section be updated afterwards?

**Comment by Joonalai** [comment]
This PostGIS [article](https://postgis.net/workshops/postgis-intro/history_tracking.html) could be helpful.

**Comment by SannaJokela** [comment]
This feature needs more information from the national level, added it to milestone RC3 (01/2021)

**Comment by SannaJokela** [comment]
Tool will not be updated in the future
